# Generated by Django 4.0.3 on 2022-03-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_profile_posts_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='...', max_length=255),
        ),
    ]
