# Generated by Django 4.0.3 on 2022-04-07 19:33

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(default='ici'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
